title: Zhe Yang
position: UKRI Fellow
affiliation: CAP, Imperial College London
affiliation_link: https://www.imperial.ac.uk/electrical-engineering/research/control-and-power/
email: mr.yangzhe@outlook.com
keywords: zhe yang, yang zhe, yangzhe, zheyang, Zhe Yang, Yang Zhe, YangZhe, ZheYang

google_scholar: https://scholar.google.com.hk/citations?user=Iw-pgigAAAAJ&hl=zh-CN&oi=ao
# github_link: https://github.com/ZhengyuZhao
linkedin: https://www.linkedin.com/in/zhe-yang-436026228/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/Zhe.jpg
google_analytics: UA-111540567-4
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
